
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author italo
 */
public class CadTurma extends javax.swing.JFrame {

    /**
     * Creates new form CadTurma
     */
    public CadTurma() throws SQLException {
        initComponents();
        popularTabelaTurmas();
        btnExcluirTurma.setEnabled(false);
        btnCadTurma.setEnabled(true);
        btnEditarTurma.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboMonitor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboPrimDia = new javax.swing.JComboBox<>();
        jComboSegDia = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboHorario = new javax.swing.JComboBox<>();
        btnCadTurma = new javax.swing.JButton();
        jTxtBuscaTurma = new javax.swing.JTextField();
        jComboPesquisaTurma = new javax.swing.JComboBox<>();
        btnEditarTurma = new javax.swing.JButton();
        btnExcluirTurma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTurma = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Cadastrar turma");

        jLabel2.setText("Selecionar monitor: ");

        jComboMonitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monitor 1", "Monitor 2", "Monitor 3", "Monitor 4" }));

        jLabel3.setText("  Dia primeira aula:");

        jComboPrimDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Segunda", "Terça", "Quarta", "Quinta", "Sexta" }));

        jComboSegDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Segunda", "Terça", "Quarta", "Quinta", "Sexta" }));

        jLabel4.setText("  Dia segunda aula:");

        jLabel5.setText("Horário: ");

        jComboHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", " " }));

        btnCadTurma.setBackground(new java.awt.Color(51, 153, 0));
        btnCadTurma.setText("Cadastrar");
        btnCadTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadTurmaActionPerformed(evt);
            }
        });

        jTxtBuscaTurma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtBuscaTurmaKeyPressed(evt);
            }
        });

        jComboPesquisaTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Monitor 1", "Monitor 2", "Monitor 3", "Monitor 4" }));
        jComboPesquisaTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPesquisaTurmaActionPerformed(evt);
            }
        });

        btnEditarTurma.setBackground(new java.awt.Color(0, 0, 141));
        btnEditarTurma.setText("Editar");
        btnEditarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTurmaActionPerformed(evt);
            }
        });

        btnExcluirTurma.setBackground(new java.awt.Color(153, 0, 0));
        btnExcluirTurma.setText("Excluir");
        btnExcluirTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTurmaActionPerformed(evt);
            }
        });

        jTableTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Monitor", "Dia primeira aula", "Dia segunda aula", "Horário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTurmaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTurma);
        if (jTableTurma.getColumnModel().getColumnCount() > 0) {
            jTableTurma.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        jButton1.setText("Cadastrar aluno");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboSegDia, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboPrimDia, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(1, 1, 1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnCadTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxtBuscaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboPesquisaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEditarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExcluirTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboPesquisaTurma)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtBuscaTurma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarTurma)
                    .addComponent(btnExcluirTurma))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboPrimDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboSegDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCadTurma))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadTurmaActionPerformed
        String monitor = jComboMonitor.getSelectedItem().toString();
        String primeiroDia = jComboPrimDia.getSelectedItem().toString();
        String segundoDia = jComboSegDia.getSelectedItem().toString();
        String horario = jComboHorario.getSelectedItem().toString();

        try {
            Conexao con = new Conexao();
            Statement st = con.conexao.createStatement();

            String sql = "INSERT INTO turma (monitor, primeira_aula, segunda_aula, horario) VALUES ('" + monitor + "', '" + primeiroDia + "', '" + segundoDia + "', '" + horario + "')";

            if (st.execute(sql)) {
                JOptionPane.showMessageDialog(null, "OPS! Tivemos um erro aqui.");
                System.out.println("Teste erro");
            } else {
                JOptionPane.showMessageDialog(null, "Dados inseridos com sucesso!");
                System.out.println("Teste sucesso");
                popularTabelaTurmas();
                limparTurma();
            }
        } catch (SQLException ex) {
            Logger.getLogger(CadTurma.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCadTurmaActionPerformed

    private void jTxtBuscaTurmaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtBuscaTurmaKeyPressed
        try {
            popularTabelaTurmas();
        } catch (SQLException ex) {
            Logger.getLogger(CadTurma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTxtBuscaTurmaKeyPressed

    private void jComboPesquisaTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPesquisaTurmaActionPerformed
        try {
            popularTabelaTurmas();
        } catch (SQLException ex) {
            Logger.getLogger(CadTurma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboPesquisaTurmaActionPerformed

    private void btnExcluirTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTurmaActionPerformed
        int linha = jTableTurma.getSelectedRow();
        String id = jTableTurma.getValueAt(linha, 0).toString();

        int confirmacao = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir a linha?");

        if (confirmacao == 0) {
            try {
                Conexao con = new Conexao();
                Statement st = con.conexao.createStatement();
                String sqlDelete = "DELETE FROM turma WHERE id = " + id;

                if (st.execute(sqlDelete)) {
                    JOptionPane.showMessageDialog(null, "Não foi possível excluir a linha!");
                } else {
                    JOptionPane.showMessageDialog(null, "Deletado com sucesso!");
                    limparTurma();
                    popularTabelaTurmas();
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "ERRO! Você precisa desassociar todos os alunos dessa turma antes de excluir.");
            }
        }
    }//GEN-LAST:event_btnExcluirTurmaActionPerformed

    private void btnEditarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTurmaActionPerformed
        int row = jTableTurma.getSelectedRow();
        String id = jTableTurma.getValueAt(row, 0).toString();

        String monitor = jComboMonitor.getSelectedItem().toString();
        String primeiroDia = jComboPrimDia.getSelectedItem().toString();
        String segundoDia = jComboSegDia.getSelectedItem().toString();
        String horario = jComboHorario.getSelectedItem().toString();

        try {
            Conexao con = new Conexao();
            Statement st = con.conexao.createStatement();

            String sql = "UPDATE turma SET "
                    + "monitor='" + monitor + "',"
                    + "primeira_aula='" + primeiroDia + "',"
                    + "segunda_aula='" + segundoDia + "',"
                    + "horario='" + horario + "'"
                    + " WHERE id = " + id;
            
            if (st.executeUpdate(sql) == 1) {
                    JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
                    popularTabelaTurmas();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao alterar");
                }

        } catch (SQLException ex) {
            Logger.getLogger(CadTurma.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEditarTurmaActionPerformed

    private void jTableTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTurmaMouseClicked
        btnExcluirTurma.setEnabled(true);
        btnCadTurma.setEnabled(false);
        btnEditarTurma.setEnabled(true);

        int row = jTableTurma.getSelectedRow();
        String id = jTableTurma.getValueAt(row, 0).toString();
        String monitor = jTableTurma.getValueAt(row, 1).toString();
        String primeiroDia = jTableTurma.getValueAt(row, 2).toString();
        String segundoDia = jTableTurma.getValueAt(row, 3).toString();
        String horario = jTableTurma.getValueAt(row, 4).toString();

        jComboMonitor.setSelectedItem(monitor);
        jComboPrimDia.setSelectedItem(primeiroDia);
        jComboSegDia.setSelectedItem(segundoDia);
        jComboHorario.setSelectedItem(horario);
    }//GEN-LAST:event_jTableTurmaMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        btnExcluirTurma.setEnabled(false);
        btnCadTurma.setEnabled(true);
        btnEditarTurma.setEnabled(false);
        limparTurma();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        try {
            CadAluno ca = new CadAluno();
            ca.setVisible(true);
        
        } catch (SQLException ex) {
            Logger.getLogger(CadTurma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadTurma().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CadTurma.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadTurma;
    private javax.swing.JButton btnEditarTurma;
    private javax.swing.JButton btnExcluirTurma;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboHorario;
    private javax.swing.JComboBox<String> jComboMonitor;
    private javax.swing.JComboBox<String> jComboPesquisaTurma;
    private javax.swing.JComboBox<String> jComboPrimDia;
    private javax.swing.JComboBox<String> jComboSegDia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTurma;
    private javax.swing.JTextField jTxtBuscaTurma;
    // End of variables declaration//GEN-END:variables

    public void popularTabelaTurmas() throws SQLException {
        String buscaTurma = jTxtBuscaTurma.getText();
        String jComboTurma = jComboPesquisaTurma.getSelectedItem().toString();

        DefaultTableModel model = (DefaultTableModel) jTableTurma.getModel();
        model.setNumRows(0);

        Conexao con = new Conexao();
        Statement st = con.conexao.createStatement();

        String sql = "SELECT * FROM turma";

        if (!buscaTurma.isEmpty() && !jComboTurma.equals("Todos")) {
            sql += " WHERE primeira_aula LIKE '" + buscaTurma + "%' OR segunda_aula LIKE '" + buscaTurma + "%' AND monitor = '" + jComboTurma + "'";
        } else if (!jComboTurma.equals("Todos")) {
            sql += " WHERE monitor = '" + jComboTurma + "'";
        } else if (!buscaTurma.isEmpty()) {
            sql += " WHERE primeira_aula LIKE '" + buscaTurma + "%' OR segunda_aula LIKE '" + buscaTurma + "%'";
        }

        ResultSet resultado = st.executeQuery(sql);

        while (resultado.next()) {
            model.addRow(new Object[]{
                resultado.getString("id"),
                resultado.getString("monitor"),
                resultado.getString("primeira_aula"),
                resultado.getString("segunda_aula"),
                resultado.getString("horario"),});
        }
    }

    public void limparTurma() {
        jComboMonitor.setSelectedIndex(0);
        jComboHorario.setSelectedIndex(0);
        jComboPrimDia.setSelectedIndex(0);
        jComboSegDia.setSelectedIndex(0);
    }

}
