




import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Aluno
 */
public class CadEmp extends javax.swing.JFrame {

    /**
     * Creates new form CadEmp
     * @throws java.sql.SQLException
     */
    public CadEmp() throws SQLException {
        initComponents();
        popularTabelaEmprestimo();
        popularTabelaPessoas();
        popularTabelaLivros();
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnEmprestar.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextNomePesquisa = new javax.swing.JTextField();
        jComboTipoPessoa = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPessoa = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaLivro = new javax.swing.JTable();
        jTextNomePesquisa1 = new javax.swing.JTextField();
        jComboTipoLivro = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextId_livro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextData_emp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnEmprestar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaEmprestimo = new javax.swing.JTable();
        jTextNomePesquisa2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboDtdev = new javax.swing.JComboBox<>();
        jComboDv = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jTextNomePesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomePesquisaActionPerformed(evt);
            }
        });
        jTextNomePesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextNomePesquisaKeyPressed(evt);
            }
        });

        jComboTipoPessoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo pessoa", "1°Ano", "2°Ano", "3°Ano", "Professor" }));
        jComboTipoPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoPessoaActionPerformed(evt);
            }
        });

        tabelaPessoa.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tabelaPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CURSO", "SÉRIE", "MATRICULA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPessoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPessoa);

        tabelaLivro.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tabelaLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID LIVRO", "NOME LIVRO", "AUTOR", "ANO", "GENERO", "EDICAO", "ESTOQUE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaLivroMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaLivro);

        jTextNomePesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomePesquisa1ActionPerformed(evt);
            }
        });
        jTextNomePesquisa1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextNomePesquisa1KeyPressed(evt);
            }
        });

        jComboTipoLivro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboTipoLivro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Científico", "Filosofia", "Ficção", "História", "Poesia" }));
        jComboTipoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoLivroActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Emprestimo");

        jLabel8.setText("ATENÇÃO! Preencha os campos \"cliente\" e \"livro\" clicando no registro,encontrado na área de pesquisa.");

        jLabel2.setText("ID do cliente: ");

        jTextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdActionPerformed(evt);
            }
        });

        jLabel3.setText("ID do livro: ");

        jLabel4.setText("Data do emprestimo:(d/m/a)");

        jLabel5.setText("Data de Devolução: ");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEmprestar.setText("Emprestar");
        btnEmprestar.setPreferredSize(new java.awt.Dimension(80, 40));
        btnEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setPreferredSize(new java.awt.Dimension(80, 40));
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });

        tabelaEmprestimo.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        tabelaEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_EMPRESTIMO", "ID", "ID_LIVRO", "DATA_EMP", "DATA_DEV"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEmprestimoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaEmprestimo);

        jTextNomePesquisa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomePesquisa2ActionPerformed(evt);
            }
        });
        jTextNomePesquisa2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextNomePesquisa2KeyPressed(evt);
            }
        });

        jComboDtdev.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dias", "semanal", "quizenal", "mensal" }));
        jComboDtdev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboDtdevActionPerformed(evt);
            }
        });

        jComboDv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboDv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Geral", "dias", "semanal", "quizenal", "mensal" }));
        jComboDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboDvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextNomePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboTipoPessoa, 0, 185, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextNomePesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboTipoLivro, 0, 157, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(314, 314, 314))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(515, 515, 515)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEmprestar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(1, 1, 1)
                                .addComponent(jTextId_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextData_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jComboDtdev, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextNomePesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboDv, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboTipoPessoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboTipoLivro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNomePesquisa1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNomePesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 19, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextNomePesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboDv, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextId_livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextData_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboDtdev, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEmprestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNomePesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomePesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomePesquisaActionPerformed

    private void jTextNomePesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNomePesquisaKeyPressed
        try {
            popularTabelaEmprestimo();
        } catch (SQLException ex) {
            Logger.getLogger(CadEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            popularTabelaPessoas();
        } catch (SQLException ex) {
            Logger.getLogger(CadEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            popularTabelaLivros();
        } catch (SQLException ex) {
            Logger.getLogger(CadEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextNomePesquisaKeyPressed

    private void jComboTipoPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoPessoaActionPerformed
        
        
        try {
            popularTabelaPessoas();
        } catch (SQLException ex) {
            Logger.getLogger(CadEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }//GEN-LAST:event_jComboTipoPessoaActionPerformed

    private void tabelaPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPessoaMouseClicked
        
        
        int row = tabelaPessoa.getSelectedRow();
        String id = tabelaPessoa.getValueAt(row, 0).toString();
        String nome = tabelaPessoa.getValueAt(row, 1).toString();
        String curso = tabelaPessoa.getValueAt(row, 2).toString();
        String serie = tabelaPessoa.getValueAt(row, 3).toString();
        String matricula = tabelaPessoa.getValueAt(row, 4).toString();

        jTextId.setText(id);
        

    }//GEN-LAST:event_tabelaPessoaMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        
        
    }//GEN-LAST:event_jPanel1MouseClicked

     
    private void tabelaLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaLivroMouseClicked
        

        int row = tabelaLivro.getSelectedRow();
        String id_livro = tabelaLivro.getValueAt(row, 0).toString();
        String nome_livro= tabelaLivro.getValueAt(row, 1).toString();
        String autor= tabelaLivro.getValueAt(row, 2).toString();
        String ano = tabelaLivro.getValueAt(row, 3).toString();
        String genero = tabelaLivro.getValueAt(row, 4).toString();
        String edicao = tabelaLivro.getValueAt(row, 5).toString();
        String estoque = tabelaLivro.getValueAt(row, 6).toString();
        
        jTextId_livro.setText(id_livro);

        
    }//GEN-LAST:event_tabelaLivroMouseClicked

    private void jTextNomePesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomePesquisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomePesquisa1ActionPerformed

    private void jTextNomePesquisa1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNomePesquisa1KeyPressed

        try {
            popularTabelaEmprestimo();
        } catch (SQLException ex) {
            Logger.getLogger(CadEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            popularTabelaLivros();
        } catch (SQLException ex) {
            Logger.getLogger(CadEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            popularTabelaPessoas();
        } catch (SQLException ex) {
            Logger.getLogger(CadEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jTextNomePesquisa1KeyPressed

    private void jComboTipoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoLivroActionPerformed

        
        try {
            popularTabelaLivros();
        } catch (SQLException ex) {
            Logger.getLogger(CadEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

    }//GEN-LAST:event_jComboTipoLivroActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestarActionPerformed
        String id= jTextId.getText();
        String id_livro= jTextId_livro.getText();
        String data_emp =  jTextData_emp.getText();
        String data_dev = jComboDtdev.getSelectedItem().toString();
        

        if (id.equals("") || id_livro.equals("")|| data_emp.equals("")|| data_dev.equals("")) {
            JOptionPane.showMessageDialog(null, "OPS! Preencha todos os campos corretamente.");
        } else {
            try {
                Conexao con = new Conexao();

                Statement st = con.conexao.createStatement();

                String sql = "INSERT INTO emprestimo (id, id_livro, data_emp,  data_dev) VALUES ('" + id+ "', '" + id_livro+ "', '" + data_emp + "', '" + data_dev + "')";

                if (st.execute(sql)) {
                    JOptionPane.showMessageDialog(null, "OPS! Tivemos um erro aqui.");
                    System.out.println("Teste erro");
                } else {
                    JOptionPane.showMessageDialog(null, "Dados inseridos com sucesso!");
                    System.out.println("Teste sucesso");
                    Emp_limpar();
                    popularTabelaEmprestimo();
                }

            } catch (Exception e) {
                System.out.println("Erro no try");
            }
        }
        
    }//GEN-LAST:event_btnEmprestarActionPerformed

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
       
    }//GEN-LAST:event_btnAlterarMouseClicked

    private void jTextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdActionPerformed

    private void tabelaEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEmprestimoMouseClicked
       
        int row = tabelaEmprestimo.getSelectedRow();
        String id = tabelaEmprestimo.getValueAt(row, 0).toString();
        String id_livro= tabelaEmprestimo.getValueAt(row, 1).toString();
        String data_emp= tabelaEmprestimo.getValueAt(row, 2).toString();
        String data_dev = tabelaEmprestimo.getValueAt(row, 3).toString();
        
        

        jTextId.setText(id);
        jTextId_livro.setText(id_livro);
        jTextData_emp.setText(data_emp);
        jComboDtdev.setSelectedItem(data_dev);
    }//GEN-LAST:event_tabelaEmprestimoMouseClicked

    private void jTextNomePesquisa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomePesquisa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomePesquisa2ActionPerformed

    private void jTextNomePesquisa2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNomePesquisa2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomePesquisa2KeyPressed

    private void jComboDtdevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboDtdevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboDtdevActionPerformed

    private void jComboDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboDvActionPerformed
        try {
            popularTabelaEmprestimo();        // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(CadEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboDvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new CadEmp().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CadEmp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnEmprestar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox<String> jComboDtdev;
    private javax.swing.JComboBox<String> jComboDv;
    private javax.swing.JComboBox<String> jComboTipoLivro;
    private javax.swing.JComboBox<String> jComboTipoPessoa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextData_emp;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextId_livro;
    private javax.swing.JTextField jTextNomePesquisa;
    private javax.swing.JTextField jTextNomePesquisa1;
    private javax.swing.JTextField jTextNomePesquisa2;
    private javax.swing.JTable tabelaEmprestimo;
    private javax.swing.JTable tabelaLivro;
    private javax.swing.JTable tabelaPessoa;
    // End of variables declaration//GEN-END:variables
public void popularTabelaPessoas() throws SQLException {
        String nomeBuscado = jTextNomePesquisa.getText();
        String tipoPessoa = jComboTipoPessoa.getSelectedItem().toString();

        DefaultTableModel model = (DefaultTableModel) tabelaPessoa.getModel();
        model.setNumRows(0);

        Conexao con = new Conexao();

        Statement st = con.conexao.createStatement();

        String sql = "SELECT * FROM pessoas";

        if (!nomeBuscado.isEmpty() && !tipoPessoa.equals("Tipo pessoa")) {
            sql += " WHERE nome LIKE '" + nomeBuscado + "%' AND serie = '" + tipoPessoa + "'";
        } else if (!tipoPessoa.equals("Tipo pessoa")) {
            sql += " WHERE serie = '" + tipoPessoa + "'";
        } else if (!nomeBuscado.isEmpty()) {
            sql += " WHERE nome LIKE '" + nomeBuscado + "%'";
        }

        ResultSet resultado = st.executeQuery(sql);

        while (resultado.next()) {
            model.addRow(new Object[]{
                resultado.getString("id"),
                resultado.getString("nome"),
                resultado.getString("curso"),
                resultado.getString("serie"),
                resultado.getString("matricula"),});
        }

    }

public void popularTabelaLivros() throws SQLException {
        String nomeLivro = jTextNomePesquisa1.getText();
        String tipoLivro = jComboTipoLivro.getSelectedItem().toString();

        DefaultTableModel model = (DefaultTableModel) tabelaLivro.getModel();
        model.setNumRows(0);

        Conexao con = new Conexao();

        Statement st = con.conexao.createStatement();

        String sql = "SELECT * FROM livro";

        if (!nomeLivro.isEmpty() && !tipoLivro.equals("Todos")) {
            sql += " WHERE nome_livro LIKE '" + nomeLivro + "%' AND genero = '" + tipoLivro + "'";
        } else if (!tipoLivro.equals("Todos")) {
            sql += " WHERE genero = '" + tipoLivro + "'";
        } else if (!nomeLivro.isEmpty()) {
            sql += " WHERE nome_livro LIKE '" + nomeLivro + "%'";
        }

        ResultSet resultado = st.executeQuery(sql);

        while (resultado.next()) {
            model.addRow(new Object[]{
                resultado.getString("id_livro"),
                resultado.getString("nome_livro"),
                resultado.getString("autor"),
                resultado.getString("ano"),
                resultado.getString("genero"),
                resultado.getString("edicao"),
                resultado.getString("estoque"),});
        }

    }

   public void popularTabelaEmprestimo() throws SQLException {
      

    }
        
    public void Emp_limpar() {
        jTextId.setText("");
        jTextId_livro.setText("");
        jTextData_emp.setText("");
        jComboDtdev.setSelectedIndex(0);
        jTextNomePesquisa2.setText("");
        
    }
}
